name: Cypress Tests

on: push

jobs:
  run-cypress:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i cypress@13

      - name: Run Cypress test
        run: npx cypress run --spec "cypress/e2e/rds.cy.js" --browser chrome --headless --config-file cypress/cypress.config.js

      - name: Store screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Store videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
