name: Cypress Tests

on: push

jobs:
  run-cypress:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installer les dépendances
      - name: Install Cypress
        run: npm install cypress --save-dev

      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress/e2e/rds.cy.js"
          browser: chrome
          headed: false
          record: false
          publish-summary: true
        continue-on-error: true

      # Upload screenshots
      - name: Store screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload videos
      - name: Store videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
