on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choisir une option"
        required: true
        type: choice
        options:
          - login (avec option spéciale)
          - login (sans option spéciale)
          - deploy
