on:
  workflow_dispatch:
    inputs:
      scenario:
        description: "Quel scénario exécuter ?"
        required: true
        default: "login"
        type: choice
        options:
          - login
          - mdp_oublie

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run test script
        run: |
          echo "Scénario choisi: ${{ github.event.inputs.scenario }}"
          ./scripts/test.sh ${{ github.event.inputs.scenario }}
